### ISSUE TITLE
Fails to validate Bee Waggle data

### ISSUE THREAD

**Issue by siamakz** [alan-turing-institute/TCPD#1]
Hi,

upon running "make", I am getting the following error:

tcpd.bee_waggle_6.ValidationError: Validating the file './datasets/bee_waggle_6/bee_waggle_6.json' failed. 
Please raise an issue on the GitHub page for this project if the error persists.
make: *** [collect] Error 1

Can I do this dataset manually?

**Comment by siamakz** [comment]
BTW, bee waggle is the only one failing! I successfully got the rest.

**Comment by GjjvdBurg** [comment]
Hi @siamakz, thank you for your interest in the dataset and thanks for reporting this issue! This is really helpful. There are a few possible things that could cause this error. I'd appreciate your help in tracking it down so I can improve the script for everyone.

First, was the ``psslds.zip`` file downloaded correctly? It should be in the ``datasets/bee_waggle_6`` directory. If it's not, please see the steps below under "downloading psslds.zip". If it is, you can run ``python get_bee_waggle_6.py`` and it should generate the ``bee_waggle_6.json`` file.

If this still fails, it might be because of rounding errors. Could you upload the resulting ``bee_waggle_6.json`` file (you can attach a file to your comments here on Github)? You may need to remove the ``@validate(MD5_JSON, MD5_JSON_2)`` line from ``get_bee_waggle_6.py`` and run the script again.

**Downloading psslds.zip**

You can manually download the dataset by following these steps:

1. Download the ``psslds.zip`` file from this url: https://web.archive.org/web/20191114130815if_/https://www.cc.gatech.edu/%7Eborg/ijcv_psslds/psslds.zip 
2. Place the file in ``datasets/bee_waggle_6``
3. Go to that directory (``cd datasets/bee_waggle_6``) and run ``python get_bee_waggle_6.py``. If you've used virtualenv make sure to activate that first. This should generate the ``bee_waggle_6.json`` file.

Please let me know if the steps above worked! In the meantime I'll try to find out how to make this process more robust.

**Comment by siamakz** [comment]
Hi @GjjvdBurg. Thanks for your great effort for this truly needed benchmark!

 The zip file is downloaded but get_bee_waggle_6.py still raises the same error. Github doesn't allow me to attach a json file. However, here is a couple of lines (copied from different places) from it, if this helps with checking rounding error:


"label": "y",
			"type": "float",
			"raw": [
				300.0,
				297.745134994,
				290.737164696,
				293.705045364,

"label": "sin(theta)",
			"type": "float",
			"raw": [
				-0.7682212795972521,
				-0.8013976703636214,
				-0.629299000646184,

"label": "cos(theta)",
			"type": "float",
			"raw": [
				0.6401843996646285,
				0.5981319034592291,
				0.7771632825769074,
				0.6302977772506493,

**Comment by GjjvdBurg** [comment]
Thanks for the swift response! Good call on adding a few lines! The value `` 0.5981319034592291`` is ``0.598131903459229`` in my version, so that's probably the cause of the error.

Could you email me the json file? I can then add it as a alternative outcome to the script. My email is on my website.

I'm preparing a Dockerfile which should be a more reproducible way of recreating the exact dataset, and I'll look into dealing with these rounding errors from within Python as well. Thank you!

**Comment by siamakz** [comment]
Sure! Just sent it to you. Thanks for looking into it!

**Comment by GjjvdBurg** [comment]
Thanks again for reporting this issue @siamakz! I've added your file as a possible outcome of the script, with a note that there are minor differences due to rounding. I've further replaced the validation error with a warning, as I expect other systems will have yet other possible rounding outcomes.
